apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2  # número de réplicas/pods desejados
  selector:
    matchLabels:
      app: lanchonete-app
  template:
    metadata:
      labels:
        app: lanchonete-app
    spec:
      containers:
        - name: lanchonete-app
          image: lanchonete-app:1.0  # nome e tag
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/dataBaseLanchonete
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
