version: '3'
services:
   postgres:
      image: 'postgres:latest'
      environment:
         POSTGRES_DB: dataBaseLanchonete
         POSTGRES_PASSWORD: secret
         POSTGRES_USER: myuser
      ports:
        - '5432:5432'
      volumes:
        - postgres-data:/var/lib/postgresql/data

   app:
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - '8080:8080'
     depends_on:
       - postgres
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dataBaseLanchonete
       SPRING_DATASOURCE_USERNAME: myuser
       SPRING_DATASOURCE_PASSWORD: secret

volumes:
  postgres-data:
