services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dataBaseLanchonete'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
