apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer  # ou NodePort, conforme sua configuração
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: lanchonete-app
