name: pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Build Docker Image
      run: docker build -t tech_challenge_lanchonete .
      working-directory: ./

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Run the Maven verify phase
        run: |
          docker build -t tech_challenge_lanchonete .
          docker run --rm tech_challenge_lanchonete mvn --batch-mode --update-snapshots verify
  deploy-main:
    runs-on: ubuntu-latest
    environment:
      name: main
    needs: publish

    if: github.ref == 'reefs/head/stage'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy MAIN"
    
