name: pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Build Docker Image
      run: docker build -t tech_challenge_lanchonete .
      working-directory: ./

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Docker Container
        shell: bash
        run: |
          echo "Published"

  deploy-main:
    runs-on: ubuntu-latest
    environment:
      name: main
    needs: publish

    if: github.ref == 'reefs/head/stage'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy MAIN"
