name: pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Start Docker Compose Services
      run: docker-compose up -d
      working-directory: ./TechChallenge_lanchonete/src/main/java/com/techChallenge/lanchonete
  
    - name: Build with Docker Compose
      run: |
        docker build -t my-java-app .
        docker run --rm -v $(pwd):/app my-java-app mvn dependency:go-offline -B
        docker run --rm -v $(pwd):/app my-java-app mvn package -DskipTests
      working-directory: ./ 

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          package: '*.jar'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
